CREATE TABLE IF NOT EXISTS participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    status       VARCHAR(20) DEFAULT 'PENDING',
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT uq_request UNIQUE (event_id, requester_id)
);
